arenaCompare: 20
batch_size: 107
checkpoint: checkpoint_last_attempt
checkpoint_path: task4/training/training_alphazero/checkpoint/
epochs: 20
epocs_gnn: 28
exploration_coefficient: 0.2762676287790896
hidden_dim: 128
l2_coeff: 0.0004763237075206401
learning_rate: 0.001
learning_rate_gnn: 0.001
load_examples: false
load_folder_file_0: checkpoint_last_attempt
load_folder_file_1: checkpoint_0
load_model: false
lr: 0.0019978088056114103
maxlenOfQueue: 80000
nn_depth: 20
nn_width: 265
numEpisodes: 20
numIterations: 1000
numItersForTrainExamplesHistory: 10000
numMCTSSimsArena: 5
numMCTSSimsTournament: 7
num_MCTS_sims: 10
num_channels: 92
num_cols: 7
num_rows: 7
resultsFilePath: resultsIteration_last_attempt.csv
saveResults: true
tempThreshold: 35
tournament_file_name: best.weights.h5
tournament_folder: /
updateThreshold: 0.55
weight_decay: 1e-4
